# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c07a950d79391fed9c8e9a5de650f84b79bcf32f4a016fd090600e9502943f767b9a26a8ca94cb00cbc28f6f7beaf26ad77973ae64da7d5b1aa5860aa177963

test:
  secret_key_base: b1909e5599155c3afb68dae6d962a964364eccb2fb87398de882dc121f314719ed9b5d40b68c3fcccb01d612723e18a3667bcb8c4f1e0abd48818b9cc24233bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
